install.packages("remotes")
remotes::install_github(repo = "laduplessis/beastio", dependencies=TRUE)
install.packages("coda", repos="https://packagemanager.posit.co/cran/2020-09-30", dependencies=TRUE)
install.packages("cowplot", repos="https://packagemanager.posit.co/cran/2020-12-30", dependencies=TRUE)
install.packages("data.table", repos="https://packagemanager.posit.co/cran/2023-02-17", dependencies=TRUE)
install.packages("dplyr", repos="https://packagemanager.posit.co/cran/2023-04-20", dependencies=TRUE)
install.packages("forcats", repos="https://packagemanager.posit.co/cran/2023-01-29", dependencies=TRUE)
install.packages("ggplot2", repos="https://packagemanager.posit.co/cran/2023-08-14", dependencies=TRUE)
install.packages("ggpubr", repos="https://packagemanager.posit.co/cran/2023-02-10", dependencies=TRUE)
install.packages("ggrepel", repos="https://packagemanager.posit.co/cran/2023-02-03", dependencies=TRUE)
install.packages("ggthemes", repos="https://packagemanager.posit.co/cran/2021-01-20", dependencies=TRUE)
install.packages("BiocManager", repos="https://packagemanager.posit.co/cran/2023-02-24", dependencies=TRUE)
BiocManager::install("ggtree")
install.packages("magrittr", repos="https://packagemanager.posit.co/cran/2022-03-30", dependencies=TRUE)
install.packages("Momocs", repos="https://packagemanager.posit.co/cran/2022-04-04", dependencies=TRUE)
remotes::install_github(repo = "yesdavid/outlineR", dependencies=TRUE)
install.packages("raster", repos="https://packagemanager.posit.co/cran/2023-03-06", dependencies=TRUE)
install.packages("rcarbon", repos="https://packagemanager.posit.co/cran/2022-11-21", dependencies=TRUE)
install.packages("readr", repos="https://packagemanager.posit.co/cran/2022-10-01", dependencies=TRUE)
install.packages("RevGadgets", repos="https://packagemanager.posit.co/cran/2022-12-03", dependencies=TRUE)
install.packages("rgeos", repos="https://packagemanager.posit.co/cran/2023-03-02", dependencies=TRUE)
install.packages("rworldmap", repos="https://packagemanager.posit.co/cran/2016-02-03", dependencies=TRUE)
install.packages("sp", repos="https://packagemanager.posit.co/cran/2023-01-19", dependencies=TRUE)
install.packages("splitstackshape", repos="https://packagemanager.posit.co/cran/2019-04-21", dependencies=TRUE)
install.packages("tibble", repos="https://packagemanager.posit.co/cran/2023-03-20", dependencies=TRUE)
install.packages("tidyr", repos="https://packagemanager.posit.co/cran/2023-01-24", dependencies=TRUE)
BiocManager::install("treeio")


